name: kiloapp
version: 1.0.0+1
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

